/**
 * Static keyword entity dictionary.
 * Keys are Polymarket category names (case-insensitive match at runtime).
 * Values are arrays of entity keywords (matched case-insensitively against market titles).
 *
 * Add new keywords here as the market landscape grows.
 */
export const ENTITY_DICTIONARY: Record<string, string[]> = {
  Crypto: [
    "BTC", "Bitcoin",
    "ETH", "Ethereum",
    "SOL", "Solana",
    "XRP", "Ripple",
    "BNB",
    "DOGE", "Dogecoin",
    "ADA", "Cardano",
    "AVAX", "Avalanche",
    "MATIC", "Polygon",
    "LINK", "Chainlink",
    "DOT", "Polkadot",
    "UNI", "Uniswap",
    "ATOM",
    "LTC", "Litecoin",
    "FIL",
    "ARB", "Arbitrum",
    "OP", "Optimism",
    "SUI",
    "APT", "Aptos",
    "INJ",
  ],
  Politics: [
    "Trump",
    "Biden",
    "Harris",
    "DeSantis",
    "Republican",
    "Democrat",
    "Senate",
    "House",
    "Congress",
    "Fed", "Federal Reserve",
    "NATO",
    "Ukraine",
    "Russia",
    "China",
    "Taiwan",
    "Israel",
    "Gaza",
    "Iran",
    "North Korea",
    "EU", "European Union",
    "UK", "Britain",
    "France",
    "Germany",
  ],
  Sports: [
    "NFL",
    "NBA",
    "MLB",
    "NHL",
    "Premier League",
    "Champions League",
    "FIFA",
    "Super Bowl",
    "World Cup",
    "UFC",
    "Wimbledon",
    "F1", "Formula 1",
    "Olympics",
    "Lakers",
    "Patriots",
    "Chiefs",
    "Cowboys",
    "Yankees",
  ],
  Business: [
    "Apple", "AAPL",
    "Tesla", "TSLA",
    "Nvidia", "NVDA",
    "Microsoft", "MSFT",
    "Google", "Alphabet", "GOOG",
    "Amazon", "AMZN",
    "Meta",
    "OpenAI",
    "Anthropic",
    "SpaceX",
    "Fed", "Federal Reserve",
    "ECB",
    "S&P", "S&P 500",
    "Nasdaq",
    "Dow",
    "IPO",
    "GDP",
    "CPI",
    "interest rate",
  ],
};
